version: "3.8"
services:
  db:
    container_name: tourplanner-db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tourplanner
      POSTGRES_PASSWORD: tourplanner123